web:
  build: .
  volumes:
   - .:/app/
  links:
   - db
  ports:
   - "80:8080"
db:
  environment:
   - POSTGRES_PASSWORD=password
   - POSTGRES_USER=admin
  image: postgres
  ports:
   - "5432:5432"