FROM nginx

ADD nginx.conf /etc/nginx/nginx.conf
ADD conf.d/* /etc/nginx/conf.d/
# ADD config.sh /home/config.sh

# CMD /home/config.sh && nginx

# NOTE
# NOTE
# Mount the /var/log/nginx volme to read the logs
